name: Codecov

on:
  push:
    branches:
      - main  # ou o nome da sua branch principal

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install --user codecov
          pip install -r requirements.txt  # ou o comando para instalar suas dependências
          pip install -r requirements-dev.txt

      - name: Run tests and generate coverage report
        run: |
          pytest --cov ./src/ ./tests/ # ou o comando para executar seus testes e gerar relatório de cobertura

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Configure o CODECOV_TOKEN em suas configurações de GitHub Secrets
          verbose: true
          
